# Generated by Django 3.1 on 2020-08-28 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('polling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.polling')),
            ],
            options={
                'ordering': ('id',),
                'unique_together': {('polling', 'topping')},
            },
        ),
    ]
