# Generated by Django 3.1 on 2020-08-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='topping_amount',
            field=models.IntegerField(default=10),
        ),
    ]
